"""Reading a dump through ``tables.yaml`` — shared by import_dump.py and diff_pack.py.

Two kinds of source feed the same path (see §8 and ``sqlite_source``):

* ``kind: json``   — an AssetRipper export, addressed by JSON path
* ``kind: sqlite`` — a game database, addressed by table and column

Both end up as ``key -> (english, table_name)``, so everything downstream — import, diff,
translate, validate — is unaware of which one the strings came from.
"""

from __future__ import annotations

import json
from dataclasses import dataclass
from pathlib import Path

import yaml

from . import sqlite_source
from .sqlite_source import SqliteTableCandidate
from .tables import TableCandidate, collect_entries

KIND_JSON = "json"
KIND_SQLITE = "sqlite"


@dataclass(frozen=True)
class TableSpec:
    file: str

    # JSON sources.
    path: str = ""
    key_path: str | None = None

    include: bool = True
    note: str | None = None

    kind: str = KIND_JSON

    # SQLite sources.
    table: str | None = None
    text_column: str | None = None
    key_column: str | None = None
    lang_column: str | None = None
    lang_value: str | None = None

    @property
    def table_name(self) -> str:
        if self.kind == KIND_SQLITE:
            return f"{self.file}:{self.table}.{self.text_column}"
        return f"{self.file}:{self.path}"

    def validate(self) -> None:
        if self.kind == KIND_JSON:
            if not self.path:
                raise ValueError(f"{self.file}: a json table needs a 'path'")
        elif self.kind == KIND_SQLITE:
            if not self.table or not self.text_column:
                raise ValueError(f"{self.file}: a sqlite table needs 'table' and 'text_column'")
        else:
            raise ValueError(f"{self.file}: unknown kind '{self.kind}' (expected json or sqlite)")


def load_table_specs(path: Path) -> list[TableSpec]:
    if not path.exists():
        raise FileNotFoundError(
            f"{path} not found. Run 'python import_dump.py --scan --dump <dir>' first, then edit "
            "the file by hand — it is the source of truth, not the heuristic."
        )

    document = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
    specs = []
    for entry in document.get("tables", []):
        spec = TableSpec(
            file=entry["file"],
            path=entry.get("path", ""),
            key_path=entry.get("key_path"),
            include=bool(entry.get("include", True)),
            note=entry.get("note"),
            kind=entry.get("kind", KIND_JSON),
            table=entry.get("table"),
            text_column=entry.get("text_column"),
            key_column=entry.get("key_column"),
            lang_column=entry.get("lang_column"),
            lang_value=entry.get("lang_value"),
        )
        spec.validate()
        specs.append(spec)

    return specs


def write_table_specs(
    path: Path,
    json_candidates: list[TableCandidate],
    sqlite_candidates: list[SqliteTableCandidate] | None = None,
) -> None:
    tables: list[dict] = []

    for candidate in json_candidates:
        tables.append(
            {
                "kind": KIND_JSON,
                "file": candidate.file,
                "path": candidate.path,
                "key_path": None,
                "include": candidate.include,
                "note": f"{candidate.entries} entries, {candidate.reason}",
                "samples": candidate.samples,
            }
        )

    for candidate in sqlite_candidates or []:
        tables.append(
            {
                "kind": KIND_SQLITE,
                "file": candidate.file,
                "table": candidate.table,
                "text_column": candidate.text_column,
                "key_column": candidate.key_column,
                "lang_column": candidate.lang_column,
                "lang_value": candidate.lang_value,
                "include": candidate.include,
                "note": f"{candidate.rows} rows, {candidate.reason}",
                "samples": candidate.samples,
            }
        )

    document = {
        "# note": (
            "Generated by import_dump.py --scan. Edit by hand: this file is the source of truth, "
            "the heuristic only proposes. For json tables set key_path to the sibling field "
            "holding the string key; for sqlite tables set key_column. Without one, keys fall "
            "back to JSON paths or rowids and shift whenever rows are inserted, which makes "
            "every diff after a patch report the whole table as changed."
        ),
        "tables": tables,
    }

    path.write_text(
        yaml.safe_dump(document, allow_unicode=True, sort_keys=False, width=100),
        encoding="utf-8",
    )


def _resolve(dump_dir: Path, name: str) -> Path:
    candidate = dump_dir / name
    if candidate.exists():
        return candidate

    matches = list(dump_dir.rglob(name))
    if not matches:
        raise FileNotFoundError(f"{name} is listed in tables.yaml but not present in {dump_dir}")

    return matches[0]


def read_dump(dump_dir: Path, specs: list[TableSpec]) -> dict[str, tuple[str, str]]:
    """``key -> (english, table_name)`` for every included table, whatever its kind.

    A key colliding across two tables is a configuration mistake, so it raises rather than
    letting one table quietly overwrite the other.
    """
    cache: dict[str, object] = {}
    entries: dict[str, tuple[str, str]] = {}

    for spec in specs:
        if not spec.include:
            continue

        file_path = _resolve(dump_dir, spec.file)

        if spec.kind == KIND_SQLITE:
            pairs = sqlite_source.read_table(
                file_path,
                table=spec.table,
                text_column=spec.text_column,
                key_column=spec.key_column,
                lang_column=spec.lang_column,
                lang_value=spec.lang_value,
            )
        else:
            if str(file_path) not in cache:
                cache[str(file_path)] = json.loads(file_path.read_text(encoding="utf-8"))

            pairs = collect_entries(
                cache[str(file_path)],
                spec.path,
                spec.key_path,
                key_prefix=f"{spec.file}:" if spec.key_path is None else "",
            )

        for key, value in pairs:
            if not value.strip():
                continue
            if key in entries and entries[key][0] != value:
                raise ValueError(
                    f"key '{key}' appears in two tables with different text "
                    f"({entries[key][1]} and {spec.table_name}); give one of them a key_path"
                )
            entries[key] = (value, spec.table_name)

    return entries
