"""Reading a dump through ``tables.yaml`` — shared by import_dump.py and diff_pack.py."""

from __future__ import annotations

import json
from dataclasses import dataclass
from pathlib import Path

import yaml

from .tables import TableCandidate, collect_entries


@dataclass(frozen=True)
class TableSpec:
    file: str
    path: str
    key_path: str | None = None
    include: bool = True
    note: str | None = None

    @property
    def table_name(self) -> str:
        return f"{self.file}:{self.path}"


def load_table_specs(path: Path) -> list[TableSpec]:
    if not path.exists():
        raise FileNotFoundError(
            f"{path} not found. Run 'python import_dump.py --scan --dump <dir>' first, then edit "
            "the file by hand — it is the source of truth, not the heuristic."
        )

    document = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
    specs = []
    for entry in document.get("tables", []):
        specs.append(
            TableSpec(
                file=entry["file"],
                path=entry["path"],
                key_path=entry.get("key_path"),
                include=bool(entry.get("include", True)),
                note=entry.get("note"),
            )
        )

    return specs


def write_table_specs(path: Path, candidates: list[TableCandidate]) -> None:
    document = {
        "# note": (
            "Generated by import_dump.py --scan. Edit by hand: this file is the source of truth, "
            "the heuristic only proposes. Set key_path to the sibling field holding the string "
            "key — without it keys fall back to JSON paths and shift when entries are inserted."
        ),
        "tables": [
            {
                "file": candidate.file,
                "path": candidate.path,
                "key_path": None,
                "include": candidate.include,
                "note": f"{candidate.entries} entries, {candidate.reason}",
                "samples": candidate.samples,
            }
            for candidate in candidates
        ],
    }

    path.write_text(
        yaml.safe_dump(document, allow_unicode=True, sort_keys=False, width=100),
        encoding="utf-8",
    )


def read_dump(dump_dir: Path, specs: list[TableSpec]) -> dict[str, tuple[str, str]]:
    """``key -> (english, table_name)`` for every included table.

    A key colliding across two tables is a configuration mistake, so it raises rather than
    letting one table quietly overwrite the other.
    """
    cache: dict[str, object] = {}
    entries: dict[str, tuple[str, str]] = {}

    for spec in specs:
        if not spec.include:
            continue

        file_path = dump_dir / spec.file
        if not file_path.exists():
            matches = list(dump_dir.rglob(spec.file))
            if not matches:
                raise FileNotFoundError(f"{spec.file} is listed in tables.yaml but not present in {dump_dir}")
            file_path = matches[0]

        if str(file_path) not in cache:
            cache[str(file_path)] = json.loads(file_path.read_text(encoding="utf-8"))

        for key, value in collect_entries(
            cache[str(file_path)],
            spec.path,
            spec.key_path,
            key_prefix=f"{spec.file}:" if spec.key_path is None else "",
        ):
            if not value.strip():
                continue
            if key in entries and entries[key][0] != value:
                raise ValueError(
                    f"key '{key}' appears in two tables with different text "
                    f"({entries[key][1]} and {spec.table_name}); give one of them a key_path"
                )
            entries[key] = (value, spec.table_name)

    return entries
