<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>CznTranslator.Sync</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\CznTranslator.Core\CznTranslator.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="CznTranslator.Tests" />
  </ItemGroup>

</Project>
